#!/bin/bash
. $(dirname "$0")/lib/lib.bash

#CSVFILE=$1
#POSTFIX=$2
#GROUP_FILE=$3
#DST_DIR=$4
SPLITER=","
TPL_DIR=$(dirname $0)/../templates/channels

perv_mac=

first_line="$(head -1 ${CSVFILE})"
col_chan=$(get_column "chan" "${first_line}" "${SPLITER}")

printf "; Autogenerated conf file\n\n" > ${DST_DIR}/sip_${TPL_PREFIX}${POSTFIX}.conf

while read line; do
  status=$(echo ${line} | cut -d, -f1)

  if [[ "${status}" != "+" ]]; then
    continue
  fi

  export_vars "${first_line}" "${line}"
  file_tpl="${TPL_DIR}/${TPL_PREFIX}${T_CHAN}.tpl"
  if [[ ! -e ${file_tpl} ]]; then
    echo WARNING: there is no template for chan:${T_CHAN} number:${T_NUMBER}
    continue
  fi

  envsubst < ${file_tpl} >> ${DST_DIR}/${T_CHAN,,}_${TPL_PREFIX}${POSTFIX}.conf
  unset ${!T_@}
  printf "."
done <<< "$(tail -n +2 ${CSVFILE})"

echo Done!




